name: Snyk SCA Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    name: Snyk SCA Scan
    steps:      
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk SCA Test
        run: snyk test --severity-threshold=medium --fail-on=upgradeable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
